[project]
name = "user-service"
version = "0.1.0"
description = "Service with user endpoints"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
]
